# Generated by Django 5.1 on 2024-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0x....', help_text='Blockchain wallet address', max_length=255, unique=True),
        ),
    ]
