# Generated by Django 5.1 on 2024-09-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_time_per_week',
            field=models.IntegerField(blank=True, help_text='Time available for studying in hours per week', null=True),
        ),
    ]
