# Generated by Django 5.1 on 2024-09-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_alter_user_available_time_per_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='book',
            name='file_name',
            field=models.CharField(default='blockchain_book.pdf', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='embedding_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
