# Generated by Django 5.1 on 2024-09-03 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_remove_book_pdf_file_book_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
